pro_tube.load_initial_data=false

spring.datasource.url=jdbc:postgresql://localhost:5432/${ENV_PROTUBE_DB}
spring.datasource.username=${ENV_PROTUBE_DB_USER}
spring.datasource.password=${ENV_PROTUBE_DB_PWD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.prefix=classpath:/static/