spring.application.name=protube-back
server.port=8080
spring.profiles.active=${ENV_PROTUBE_PROFILE}

#security
application.security.jwt.secretkey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.token-prefix=Bearer
# a week in milliseconds
application.security.jwt.expiration=604800000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Before running the process you must have this system-level environment variable set: ENV_PROTUBE_STORE_DIR
# It must hold the absolute path to the directory containing the videos (and any other file-based storage)
pro_tube.store.dir=${ENV_PROTUBE_STORE_DIR}

spring.mvc.static-path-pattern=/media/**
logging.level.org.springframework.web=DEBUG