POST http://localhost:8080/api/users/create
content-type: application/json

{
  "name": "Luis",
  "password": "Luisaco123.",
  "email": "lacostas@edu.tecnocampus.cat"
}

###
POST http://localhost:8080/authenticate
content-type: application/json

{
  "username": "Luis",
  "password": "Luisaco123."
}
> {%
    client.global.set("auth_token", response.headers.valueOf("Authorization"));
    client.log("token: " + response.headers.valueOf("Authorization"));
%}

###
GET http://localhost:8080/api/videos


###
GET http://localhost:8080/api/videos/0


###
PUT http://localhost:8080/api/videos/0
Authorization: {{auth_token}}
content-type: application/json

{
  "title": "Bruno Mars - 24K Magic",
  "description": "Test funciona bien!"
}

###
GET http://localhost:8080/media/0.webp

###
POST http://localhost:8080/api/comments
Authorization: {{auth_token}}
content-type: application/json

{
  "videoId": 100,
  "comment_text": "Al oscar no le gustwetrfasda"
}

###
PATCH http://localhost:8080/api/comments/929/text
Authorization: {{auth_token}}
content-type: application/json

{
  "text": "hola oscar"
}

###
DELETE http://localhost:8080/api/comments/929
Authorization: {{auth_token}}
content-type: application/json

###
GET http://localhost:8080/api/users/userDetails
Authorization: {{auth_token}}

###
GET http://localhost:8080/api/videos/author
Authorization: {{auth_token}}

POST http://localhost:8080/api/videos
Authorization: {{auth_token}}
content-type: application/json


###
DELETE localhost:8080/api/videos/0
Authorization: {{auth_token}}

###
GET localhost:8080/api/videos/categories

###
GET localhost:8080/api/videos/category/Music